{
    "cve": {
        "data_type": "CVE",
        "data_format": "MITRE",
        "data_version": "4.0",
        "CVE_data_meta": {
            "ID": "CVE-2025-30474",
            "ASSIGNER": "security@apache.org"
        },
        "problemtype": {
            "problemtype_data": [
                {
                    "description": [
                        {
                            "lang": "en",
                            "value": "CWE-200"
                        }
                    ]
                }
            ]
        },
        "references": {
            "reference_data": [
                {
                    "url": "https:\/\/issues.apache.org\/jira\/browse\/VFS-169",
                    "name": "https:\/\/issues.apache.org\/jira\/browse\/VFS-169",
                    "refsource": "",
                    "tags": []
                },
                {
                    "url": "https:\/\/lists.apache.org\/thread\/w6ztgnbk6ccry3470x191g3xwrpgy6f4",
                    "name": "https:\/\/lists.apache.org\/thread\/w6ztgnbk6ccry3470x191g3xwrpgy6f4",
                    "refsource": "",
                    "tags": []
                }
            ]
        },
        "description": {
            "description_data": [
                {
                    "lang": "en",
                    "value": "Exposure of Sensitive Information to an Unauthorized Actor vulnerability in Apache Commons VFS.\n\nThe FtpFileObject class can throw an exception when a file is not found, revealing the original URI in its message, which may include a password. The fix is to mask the password in the exception message\nThis issue affects Apache Commons VFS: before 2.10.0.\n\nUsers are recommended to upgrade to version 2.10.0, which fixes the issue."
                }
            ]
        }
    },
    "configurations": {
        "CVE_data_version": "4.0",
        "nodes": []
    },
    "impact": [],
    "publishedDate": "2025-03-23T15:15Z",
    "lastModifiedDate": "2025-03-23T15:15Z"
}