{
    "cve": {
        "id": "CVE-2025-4476",
        "sourceIdentifier": "secalert@redhat.com",
        "published": "2025-05-16T18:16:10.970",
        "lastModified": "2025-05-19T13:35:20.460",
        "vulnStatus": "Awaiting Analysis",
        "cveTags": [],
        "descriptions": [
            {
                "lang": "en",
                "value": "A denial-of-service vulnerability has been identified in the libsoup HTTP client library. This flaw can be triggered when a libsoup client receives a 401 (Unauthorized) HTTP response containing a specifically crafted domain parameter within the WWW-Authenticate header. Processing this malformed header can lead to a crash of the client application using libsoup. An attacker could exploit this by setting up a malicious HTTP server. If a user's application using the vulnerable libsoup library connects to this malicious server, it could result in a denial-of-service. Successful exploitation requires tricking a user's client application into connecting to the attacker's malicious server."
            },
            {
                "lang": "es",
                "value": "Se ha identificado una vulnerabilidad de denegaci\u00f3n de servicio en la librer\u00eda cliente HTTP libsoup. Esta falla puede activarse cuando un cliente libsoup recibe una respuesta HTTP 401 (No autorizado) que contiene un par\u00e1metro de dominio espec\u00edficamente dise\u00f1ado dentro del encabezado WWW-Authenticate. El procesamiento de este encabezado malformado puede provocar un bloqueo de la aplicaci\u00f3n cliente que utiliza libsoup. Un atacante podr\u00eda explotar esto configurando un servidor HTTP malicioso. Si la aplicaci\u00f3n de un usuario que utiliza la librer\u00eda libsoup vulnerable se conecta a este servidor malicioso, podr\u00eda provocar una denegaci\u00f3n de servicio. Para explotarla con \u00e9xito, es necesario enga\u00f1ar a la aplicaci\u00f3n cliente del usuario para que se conecte al servidor malicioso del atacante."
            }
        ],
        "metrics": {
            "cvssMetricV31": [
                {
                    "source": "secalert@redhat.com",
                    "type": "Secondary",
                    "cvssData": {
                        "version": "3.1",
                        "vectorString": "CVSS:3.1\/AV:N\/AC:L\/PR:N\/UI:R\/S:U\/C:N\/I:N\/A:L",
                        "baseScore": 4.3,
                        "baseSeverity": "MEDIUM",
                        "attackVector": "NETWORK",
                        "attackComplexity": "LOW",
                        "privilegesRequired": "NONE",
                        "userInteraction": "REQUIRED",
                        "scope": "UNCHANGED",
                        "confidentialityImpact": "NONE",
                        "integrityImpact": "NONE",
                        "availabilityImpact": "LOW"
                    },
                    "exploitabilityScore": 2.8,
                    "impactScore": 1.4
                }
            ]
        },
        "weaknesses": [
            {
                "source": "secalert@redhat.com",
                "type": "Secondary",
                "description": [
                    {
                        "lang": "en",
                        "value": "CWE-476"
                    }
                ]
            }
        ],
        "references": [
            {
                "url": "https:\/\/access.redhat.com\/security\/cve\/CVE-2025-4476",
                "source": "secalert@redhat.com"
            },
            {
                "url": "https:\/\/bugzilla.redhat.com\/show_bug.cgi?id=2366513",
                "source": "secalert@redhat.com"
            }
        ]
    }
}