{
    "cve": {
        "data_type": "CVE",
        "data_format": "MITRE",
        "data_version": "4.0",
        "CVE_data_meta": {
            "ID": "CVE-2023-53027",
            "ASSIGNER": "cve@kernel.org"
        },
        "problemtype": {
            "problemtype_data": [
                {
                    "description": []
                }
            ]
        },
        "references": {
            "reference_data": [
                {
                    "url": "https:\/\/git.kernel.org\/stable\/c\/12724ba38992bd045e92a9a88a868a530f89d13e",
                    "name": "https:\/\/git.kernel.org\/stable\/c\/12724ba38992bd045e92a9a88a868a530f89d13e",
                    "refsource": "",
                    "tags": []
                },
                {
                    "url": "https:\/\/git.kernel.org\/stable\/c\/7b28a8920844042ca9f44934d8f15d210ef42c75",
                    "name": "https:\/\/git.kernel.org\/stable\/c\/7b28a8920844042ca9f44934d8f15d210ef42c75",
                    "refsource": "",
                    "tags": []
                }
            ]
        },
        "description": {
            "description_data": [
                {
                    "lang": "en",
                    "value": "In the Linux kernel, the following vulnerability has been resolved:\n\nerofs: fix kvcalloc() misuse with __GFP_NOFAIL\n\nAs reported by syzbot [1], kvcalloc() cannot work with  __GFP_NOFAIL.\nLet's use kcalloc() instead.\n\n[1] https:\/\/lore.kernel.org\/r\/0000000000007796bd05f1852ec2@google.com"
                }
            ]
        }
    },
    "configurations": {
        "CVE_data_version": "4.0",
        "nodes": []
    },
    "impact": [],
    "publishedDate": "2025-03-27T17:15Z",
    "lastModifiedDate": "2025-03-27T17:15Z"
}